version: '3'

services:
  next-app:
    container_name: app_cont
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
    restart: always
    ports:
      - 3000:3000
  nginx:
    image: nginx
    container_name: nginx_cont
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    container_name: certbot_cont
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos